# Generated by Django 5.2.1 on 2025-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OlapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('area', models.FloatField(default=0)),
                ('bedrooms', models.FloatField(default=0)),
                ('bathrooms', models.FloatField(default=0)),
                ('stars', models.FloatField(blank=True, null=True)),
                ('thumbs_up', models.FloatField(blank=True, null=True)),
                ('thumbs_down', models.FloatField(blank=True, null=True)),
                ('reply_count', models.FloatField(blank=True, null=True)),
                ('best_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
